### ISSUE TITLE
batch add to yaml options

### ISSUE THREAD

**Issue by yggdrasil75** [yggdrasil75/sd-infinity-grid-generator-script#4]
https://github.com/mcmonkeyprojects/sd-infinity-grid-generator-script/issues/33
so, yeah. probably shouldnt have closed it (it was an accident) but there is still more to do, so adding this here.

**Comment by yggdrasil75** [comment]
added this and confirmed model change works. next thing to do is check that it completes properly. maybe next week I will see that.

**Comment by yggdrasil75** [comment]
another feature needed: multi gpu batch options. I have a 1080 ti and a 3090. the 1080 ti wont run 12 512x512 at a high speed, instead it would be faster at 4. I could use batch[0]: 12 batch[1]: 4 to specify batch sizes.
this would also potentially start leaning towards splitting the processing between multiple gpus. add "splitbatch" where you set it to a device id, and it will not run that set unless there are none within the specified device id.

**Comment by appleguy** [comment]
@yggdrasil75 Where can I learn about what kinds of batches are supported? Is it maybe necessary to specify certain keys in a specific order? Those restrictions would be fine if I understand them, but at the moment I get messages like:

```
merging prompts 16 - 20 of 32
prompt contains incorrect cfg_scale merge unavailable. values are: 19.0
prompt contains incorrect cfg_scale merge unavailable. values are: 19.0
prompt contains incorrect cfg_scale merge unavailable. values are: 19.0
```

**Comment by yggdrasil75** [comment]
only prompt is supported being merged. I dont know what else is handled as being able to be merged. I am looking into what else I could do to merge more but I dont know what it can handle yet. (by prompt, I mean the final resulting prompt, not the prompt parameter)

I also need to print out the first as currently it only prints out all other values… you probably have a 15 or something that prevented the other 3 from being batched.

**Comment by yggdrasil75** [comment]
alright, the logging error is fixed. also it now merges seeds as well. if prompt (after all prompt replaces and such) is different, or negative prompt is different, or seed or subseed. (I dont see anything in the txt2img that handles multiple resolutions or cfg scales. though I might be wrong)
also for prompt replace: added negative prompt replace properly, and prompt replace no longer affects negative prompts. makes it easier to set something like "scene" and replace scene in prompt with "ocean" and in nprompt with "forest" or whatever you want.
