### ISSUE TITLE
Error message when starting the webui.

### ISSUE THREAD

**Issue by hakaserver** [yggdrasil75/sd-infinity-grid-generator-script#9]
`*** Error calling: D:\SDWebui\stable-diffusion-webui\extensions\sd-infinity-grid-generator-script\scripts\gigagrid.py/ui
    Traceback (most recent call last):
      File "D:\SDWebui\stable-diffusion-webui\modules\scripts.py", line 402, in wrap_call
        return func(*args, **kwargs)
      File "D:\SDWebui\stable-diffusion-webui\extensions\sd-infinity-grid-generator-script\scripts\gigagrid.py", line 73, in ui
        listImageFiles()
      File "D:\SDWebui\stable-diffusion-webui\extensions\sd-infinity-grid-generator-script\scripts\gigagrid.py", line 28, in listImageFiles
        if ImagesCache is not None:
    NameError: name 'ImagesCache' is not defined

---
[datalog] used before defining logFile, value: [listImageFiles] done in 0.00
[listImageFiles] done in 0.00`

Message while starting the webui. The "gigagrid - in dev." shows no options when selected in the scripts dropdown, not sure if intended.

**Comment by yggdrasil75** [comment]
That can currently be ignored. gigagrid is a complete rewrite while infinity grid v2 replaces monkey4eva. please note: if you have both, then due to how python works, it may try to call from his version functions instead of my version. you need to disable 1 to use the other.

**Comment by hakaserver** [comment]
As I thought then, thanks!
For now I renamed the gigagrid.py to gigagrid.bkp to just skip it during launch.
Also removed the other fork prior to installing this one, so it should be safe 👍
